baseurl: https://benontrack.netlify.app/
languageCode: en-us
title: BenOnTrack
theme: parsa-hugo
summaryLength: '5'
paginate: 6
googleAnalytics: ''
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  address: Belgium
  author: BenOnTrack
  author_image: images/banner-img.png
  bio: I'm a traveller
  contact_form_action: '#'
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright &copy; 2020 a theme by [themefisher.com](themefisher.com)
  description: This is meta description
  email: BenOnTrack@gmail.com
  home: Home
  instafeed:
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
    enable: yes
  layout: '1'
  logo: images/logo.png
  mobile: +90 000 333 22
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/headroom/headroom.js
      - link: plugins/instafeed/instafeed.min.js
      - link: plugins/masonry/masonry.js
      - link: plugins/reading-time/readingTime.min.js
      - link: plugins/smooth-scroll/smooth-scroll.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
  preloader: yes
  search: yes
  social:
    - icon: ti-facebook
      url: '#'
    - icon: ti-twitter-alt
      url: '#'
    - icon: ti-linkedin
      url: '#'
    - icon: ti-github
      url: '#'
menu:
  main:
    - hasChildren: yes
      name: Homepage
      url: home
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Contact
      url: contact
      weight: 3
