baseurl: https://benontrack.netlify.app/
markup:
  goldmark:
    renderer:
      unsafe: true
languageCode: en-us
title: BenOnTrack
theme: parsa-hugo
summaryLength: '20'
paginate: 6
googleAnalytics: ''
disqusShortname: benontrack
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  address: Made with love in Toulouse
  author: BenOnTrack
  author_image: images/banner-img.png
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright &copy; 2021 a theme by BenOnTrack
  description: Blog about travels and tips
  email: BenOnTrack@gmail.com
  home: Home
  logo: images/logo_square_small.png
  logo_main : images/logo_main.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
      - link : plugins/blueimp/blueimp-gallery.min.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/headroom/headroom.js
      - link: plugins/instafeed/instafeed.min.js
      - link: plugins/masonry/masonry.js
      - link: plugins/reading-time/readingTime.min.js
      - link: plugins/smooth-scroll/smooth-scroll.js
      - link: plugins/search/fuse.min.js
      - link: plugins/search/mark.js
      - link: plugins/search/search.js
  preloader: yes
  search: yes
  social:
    - icon: ti-facebook
      url: 'https://www.facebook.com/benontrack'
    - icon: ti-twitter-alt
      url: 'https://twitter.com/BenOnTrack'
    - icon: ti-linkedin
      url: 'https://www.linkedin.com/in/benjaminmodave/'
    - icon: ti-github
      url: 'https://github.com/BenOnTrack'
menu:
  main:
    - name: europe
      url: categories/europe/
      weight: 1
    - name: america
      url: categories/america/
      weight: 2
    - name: asia
      url: categories/asia/
      weight: 3
    - name: africa
      url: categories/africa/
      weight: 4
    - name: Itinerary
      url: map
      weight: 5
    - name: Subscribe
      url: subscribe
      weight: 6

      
